In [1]:
import gymnasium as gym
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

Matplotlib is building the font cache; this may take a moment.


In [2]:
# creating an env of the CarRacing game
env = gym.make("CarRacing-v3", render_mode="human")

In [3]:
# Wrap with DummyVecEnv for Stable Baselines3
vec_env = DummyVecEnv([lambda: env])

In [4]:
# Create model
model = PPO("CnnPolicy", vec_env, verbose=1)

Using cpu device
Wrapping the env in a VecTransposeImage.


In [ ]:
# Train for some timesteps
model.learn(total_timesteps=100000)

In [ ]:
# Save the model
model.save("ppo_carracing")

In [3]:
# normal reset, this changes the colour scheme by default
obs, info = env.reset(seed=1)

In [13]:
def my_strategy_a(state_id):
    """
    Determines the action based on state_id.
    Args:
    state_id (int): The current state identifier.
    Returns:
    np.array: The action to take as a numpy array.
    """
    # Define actions
    action_1 = [np.array([0.0, 0.01, 0.0]), np.array([0.0, 0.0, 0.0])]
    action_2 = [np.array([-0.12, 0.00, -0.05]), np.array([0.0, 0.0, 0.0])]
    action_3 = [np.array([0.0, 0.3, 0.0]), np.array([0.0, 0.0, 0.0])]

    # Determine action based on state_id
    if state_id < 275:
        return random.choice(action_1)
    elif 275 <= state_id <= 375:
        return random.choice(action_2)
    else:
        return random.choice(action_3)

In [14]:
def my_strategy_b(state_id):
    """
    Determines the action based on state_id.
    Args:
    state_id (int): The current state identifier.
    Returns:
    np.array: The action to take as a numpy array.
    """
    # Define actions
    action_1 = np.array([0.0, 0.01, 0.0])
    action_2 = np.array([-0.12, 0.00, -0.05])
    action_3 = np.array([0.0, 0.3, 0.0])
    
    # Determine action based on state_id
    if state_id < 275:
        return action_1
    elif 275 <= state_id <= 375:
        return action_2
    else:
        return action_3

In [ ]:
# taking 500 actions
for state_id in range(500):
    # randomly choose an action from possible 5 Discrete actions
    # action = env.action_space.sample() # agent policy that uses the observation and info

    # replace the random action with the deterministic strategy
    action = my_strategy_b(state_id)
    
    # passing chosen action into step of env. Which is actually doing the action
    observation, reward, terminated, truncated, info = env.step(action)
    # print("observation", observation)
    # print("reward", reward)
    # print(observation.shape)
    # checking whether there is some termination or truncation of the game
    if terminated or truncated:
        observation, info = env.reset()

observation [[[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 202 100]
  [100 202 100]
  [100 202 100]]

 [[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 202 100]
  [100 202 100]
  [100 202 100]]

 [[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 202 100]
  [100 202 100]
  [100 202 100]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
reward -0.10000000000000142
(96, 96, 3)
observation [[[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 202 100]
  [100 202 100]
  [100 202 100]]

 [[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 202 100]
  [100 202 100]
  [100 202 100]]

 [[100 228 100]
  [100 228 100]
  [100 228 100]
  ...
  [100 202 100]
  [100 202 100]
  [100 202 1

: 